#!/bin/sh

# Which clients to use?
# (e.g. duckling01 duckling02)
CLIENT_IDS="`seq -w 01 02`"
CLIENT_PFX="duckling"

# Possible targets to measure
c2a="fe80:0000:0000:0000:021e:06ff:fe36:1fb5"
c2b="fd12:3456:789a:bcde:0000:0000:0000:0002"

# Pick which target to test
TESTTARGETIP=$c2a
# If using raw sockets, the MAC address is needed
#TESTTARGETMAC=mac_goes_here

# Interface the client will use to connect to the target.
# This must be specified for latency6 test.
IFACE="enp1s0"

# IP of the target and the port between the clients and the target
TARGET=$TESTTARGETIP
PORT=7

# Echo test: raw (ethernet protocol 6008)
# udp or tcp to port 7.
SOCKTYPE=${SOCKTYPE:-udp}
#SOCKTYPE=raw
#SOCKTYPE=tcp

# How many default samples?
SAMPLES=${SAMPLES:-10000}

# Default throughput (bandwith) range
THROUGHPUT_RANGE=${THROUGHPUT_RANGE:-"\
10000000 \
100000000 \
1000000000"}

# Packet sizes to test
PKTSIZES=${PKTSIZES:-"\
1448 \
1217 \
1120 \
1056 \
1024 \
1000 \
861 \
800 \
724 \
680 \
608 \
590 \
580 \
512 \
430 \
362 \
304 \
256 \
215 \
181 \
152 \
128 \
90 \
76 \
64"}

WARMUP=${WARMUP:-10}
COOLDOWN=`expr $SAMPLES / 1000 + 5`

case ${SOCKTYPE} in
	udp|tcp) TESTTARGET=$TESTTARGETIP
	;;
	raw)     TESTTARGET=$TESTTARGETMAC
	;;
	*)	     echo >&2 "Unknown socket type $SOCKTYPE"
		       exit 1
  ;;
esac

nclients=0
for i in $CLIENT_IDS
do
	clients="$clients --client=$CLIENT_PFX$i"
	nclients=`expr $ntclients + 1`
done

cat <<-EOF
	IP benchmark run at `date`
	Target:     $TARGET 
	Using:      $clients
	Test:       latency6
	Type:       $SOCKTYPE
	Warmup:     $WARMUP
  Cooldown:   $COOLDOWN
  Bandwidths: $THROUGHPUT_RANGE
  Pkt sizes:  $PKTSIZES
EOF

for throughput in THROUGHPUT_RANGE
do
  for pkt_size in $PKTSIZES
  do
    BPS=`expr $throughput/$nclients`
  
  	ipbench -r $clients \
      --test-target=$TESTTARGET \
      --test=latency \
  		--test-args="\
      bps=$BPS,\
      size=$i,\
      socktype=$SOCKTYPE,\
      samples=`$SAMPLES/$nclients`,\
      warmup=$WARMUP,\
      cooldown=$COOLDOWN,\
      iface=$IFACE" \
      --test-port=$PORT
  done
done
